# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __REPO_NAME__
spec:
  selector:
    matchLabels:
      app: __REPO_NAME__
  replicas: 1
  template:
    metadata:
      labels:
        app: __REPO_NAME__
    spec:
      containers:
        - name: __REPO_NAME__
          image: __DOCKER_HUB_USERNAME__/__REPO_NAME__:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: __REPO_NAME__
spec:
  type: NodePort
  selector:
    app: __REPO_NAME__
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
