const addBookInputs = {
  title: {
    type: 'text',
    name: 'title',
    id: 'title',
    label: 'Tytuł',
    regexp: /^(?!\s*$).+/,
    helperText: 'Tytuł jest wymagany',
  },
  author: {
    type: 'text',
    name: 'author',
    id: 'author',
    label: 'Autor',
    regexp: /^(?!\s*$).+/,
    helperText: 'Autor jest wymagany',
  },
  photoUrl: {
    type: 'text',
    name: 'photoUrl',
    id: 'photoUrl',
    label: 'Link do zdjęcia',
    regexp: /^(?!\s*$).+/,
    helperText: 'Link do zdjęcia jest wymagany',
  },
  year: {
    type: 'number',
    name: 'year',
    id: 'year',
    label: 'Rok premiery',
    regexp: /^(?!\s*$).+/,
    helperText: 'Rok premiery jest wymagany',
  },
  description: {
    type: 'text',
    name: 'description',
    id: 'description',
    label: 'Opis',
    regexp: /^(?!\s*$).+/,
    helperText: 'Opis jest wymagany',
  },
  numPages: {
    type: 'number',
    name: 'numPages',
    id: 'numPages',
    label: 'Liczba stron',
    regexp: /^(?!\s*$).+/,
    helperText: 'Liczba stron jest wymagana',
  },
  price: {
    type: 'number',
    name: 'price',
    id: 'price',
    label: 'Cena',
    regexp: /^(?!\s*$).+/,
    helperText: 'Cena jest wymagana',
  },
  categoryId: {
    type: 'select',
    name: 'categoryId',
    id: 'category',
    label: 'Kategoria',
    options: [],
    regexp: /^(?!\s*$).+/,
    helperText: 'Kategoria jest wymagana',
  },
  coverType: {
    type: 'select',
    name: 'coverType',
    id: 'coverType',
    label: 'Rodzaj oprawy',
    options: [
      { value: 'PAPERBACK', name: 'Miękka' },
      { value: 'HARDCOVER', name: 'Twarda' },
    ],
    regexp: /^(?!\s*$).+/,
    helperText: 'Rodzaj oprawy jest wymagany',
  },
  recommended: {
    type: 'checkbox',
    name: 'recommended',
    checked: false,
    id: 'recommended',
    label: 'Polecana',
  },
  available: {
    type: 'checkbox',
    name: 'available',
    checked: true,
    id: 'available',
    label: 'Dostępna',
  },
};

export default addBookInputs;
