const bookInputs = () => {
  return {
    title: {
      type: 'text',
      name: 'title',
      id: 'title',
      label: 'Tytuł',
      defaultValue: false,
      regexp: /^(?!\s*$).+/,
      helperText: 'Tytuł jest wymagany',
    },
    author: {
      type: 'text',
      name: 'author',
      id: 'author',
      label: 'Autor',
      defaultValue: false,
      regexp: /^(?!\s*$).+/,
      helperText: 'Autor jest wymagany',
    },
    photoUrl: {
      type: 'text',
      name: 'photoUrl',
      id: 'photoUrl',
      label: 'Link do zdjęcia',
      defaultValue: false,
      regexp: /^(?!\s*$).+/,
      helperText: 'Link do zdjęcia jest wymagany',
    },
    year: {
      type: 'number',
      name: 'year',
      id: 'year',
      label: 'Rok premiery',
      defaultValue: false,
      regexp: /^(?!\s*$).+/,
      helperText: 'Rok premiery jest wymagany',
    },
    description: {
      type: 'text',
      name: 'description',
      id: 'description',
      label: 'Opis',
      defaultValue: false,
      regexp: /^(?!\s*$).+/,
      helperText: 'Opis jest wymagany',
    },
    numPages: {
      type: 'number',
      name: 'numPages',
      id: 'numPages',
      label: 'Liczba stron',
      defaultValue: false,
      regexp: /^(?!\s*$).+/,
      helperText: 'Liczba stron jest wymagana',
    },
    price: {
      type: 'number',
      name: 'price',
      id: 'price',
      label: 'Cena',
      defaultValue: false,
      regexp: /^(?!\s*$).+/,
      helperText: 'Cena jest wymagana',
    },
    categoryId: {
      type: 'select',
      name: 'categoryId',
      id: 'category',
      label: 'Kategoria',
      options: [],
      defaultValue: false,
      regexp: /^(?!\s*$).+/,
      helperText: 'Kategoria jest wymagana',
    },
    coverType: {
      type: 'select',
      name: 'coverType',
      id: 'coverType',
      label: 'Rodzaj oprawy',
      defaultValue: false,
      options: [
        { value: 'PAPERBACK', name: 'Miękka' },
        { value: 'HARDCOVER', name: 'Twarda' },
      ],
      regexp: /^(?!\s*$).+/,
      helperText: 'Rodzaj oprawy jest wymagany',
    },
    recommended: {
      type: 'checkbox',
      name: 'recommended',
      id: 'recommended',
      defaultValue: false,
      label: 'Polecana',
    },
    available: {
      type: 'checkbox',
      name: 'available',
      id: 'available',
      defaultValue: false,
      label: 'Dostępna',
    },
  };
};

export default bookInputs;
